version: "3.8"

networks:
    laravelapp:
        driver: bridge

services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: laravelapp
        container_name: laravelapp-web
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravelapp

    nginx:
        image: nginx:latest
        container_name: laravelapp-nginx
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./:/var/www/
            - ./docker-compose/nginx/:/etc/nginx/conf.d/
        networks:
            - laravelapp