version: "3.8"

networks:
    default:
        external:
            name: laravelapp-net

services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: laravelapp
        container_name: laravelapp-web
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www

    nginx:
        image: nginx:latest
        container_name: laravelapp-nginx
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./:/var/www/
            - ./docker-compose/nginx/:/etc/nginx/conf.d/